"""Part A — emit the SQL that publishes the planned prices.

Writes work/apply_a.sql. Run it with psql yourself; this script never connects.

Every row written gets:
  * `current_prices` upserted: price, unit = the SKU's own unit, vat_included
    false (ahanonline serves ex-VAT), is_stale false, updated_at now(),
    movement reset to flat/NULL, delivery_time preserved when a row already
    existed and left to the column default ('۲۴ ساعت') when it did not.
  * a matching `price_points` row at the same instant, because the chart and
    نوسان read that table and a current_prices write without one silently
    breaks both.
  * `updated_by` NULL — 242 of the 243 rows already in current_prices carry
    NULL, so that is the convention here, and the FK is `on delete set null`
    anyway. This pass was not performed by a signed-in admin.
"""
import json, sys
sys.path.insert(0, 'work')
from ulid import ulid

plan = json.load(open('work/plan_a.json', encoding='utf-8'))
writes = [p for p in plan if p['action'] == 'write']

# theoretical_weight_kg corrections — see the report's weight section.
# 6 m branch weights, ASME B36.10M schedule 40 seamless (the schedule ahanonline
# quotes its domestic اهواز مانیسمان at). Old values were the ROUND-BAR formula
# d²/162 × 12 applied to the inch NUMBER as if it were millimetres, which is why
# a 3-inch seamless branch was on file as 0.7 kg.
WEIGHT_FIXES = {
    'لوله مانیسمان ۳ اینچ': 67.7,
    'لوله مانیسمان ۴ اینچ': 96.4,
    'لوله مانیسمان ۵ اینچ': 130.6,
    'لوله مانیسمان ۶ اینچ': 169.6,
    'لوله مانیسمان ۸ اینچ': 255.3,
}

out = ["-- Part A: republish ahanonline-sourced prices (2026-08-19 data).",
       "-- Generated by work/apply_a.py. See the audit report for provenance per row.",
       'BEGIN;',
       '']

out.append('-- 1. theoretical_weight_kg corrections (physical constants, logged old -> new)')
for name, kg in WEIGHT_FIXES.items():
    out.append("UPDATE skus SET theoretical_weight_kg = %s, updated_at = now() "
               "WHERE name = '%s' AND is_active;" % (kg, name))
out.append('')

out.append('-- 2. prices')
for p in writes:
    pid = ulid()
    dt = ("'%s'" % p['delivery_time'].replace("'", "''")) if p['delivery_time'] else "'۲۴ ساعت'"
    out.append(
        "INSERT INTO current_prices (sku_id, price, unit, delivery_time, vat_included, "
        "movement_pct, movement_dir, updated_at, updated_by, is_stale) VALUES "
        "('%s', %d, '%s', %s, false, NULL, 'flat', now(), NULL, false) "
        "ON CONFLICT (sku_id) DO UPDATE SET price = EXCLUDED.price, unit = EXCLUDED.unit, "
        "vat_included = false, movement_pct = NULL, movement_dir = 'flat', "
        "updated_at = now(), is_stale = false;"
        % (p['sku_id'], p['price'], p['unit'], dt))
    out.append(
        "INSERT INTO price_points (id, sku_id, price, unit, at) VALUES "
        "('%s', '%s', %d, '%s', now());" % (pid, p['sku_id'], p['price'], p['unit']))
out.append('')
out.append('COMMIT;')

open('work/apply_a.sql', 'w', encoding='utf-8').write('\n'.join(out) + '\n')
print('rows to write:', len(writes))
print('weight fixes :', len(WEIGHT_FIXES))
print('sql           : work/apply_a.sql')
