/**
 * What this conversation has already established.
 *
 * WHY A SECOND MEMORY. There is already a rolling summary (conversation.ts) —
 * a paragraph of Persian prose the model writes about the older turns. It is
 * good at what it is for (keeping a long chat coherent) and structurally bad
 * at this: it is lossy, it is regenerated by a model, and it is explicitly
 * forbidden from containing numbers. None of that can drive a UI decision. The
 * landed-cost column on the comparison card either has a city or it does not,
 * and «probably Mashhad, per the summary» is not a city.
 *
 * So the facts a later turn has to ACT on are kept as fields: the product line
 * under discussion, its size, the mill, the tonnage, and the delivery city.
 * They are written by the tools as they resolve each one (a product the
 * catalog matched is a fact, not an inference) and by a deterministic city
 * scan over the visitor's own words.
 *
 * WHY IT IS NOT PII. Only catalog vocabulary and a city name from a fixed
 * list ever land here — never a name, a mobile, or an address. That is
 * deliberate: this rides in Redis with a TTL and is injected into a model
 * prompt, and neither is a place to put a customer's identity. Who the
 * visitor is comes from the session at request time (see `identityFact`), so
 * it is always current and never stored twice.
 *
 * Storage mirrors leadDraft.ts: Redis when configured, an in-process Map
 * otherwise. Losing it costs the visitor one repeated sentence, never an
 * error, so every path here is best-effort by design.
 */
import { cacheGetJson, cacheSetJson } from '@/lib/server/redis';
import { CITIES } from '@/lib/data/logistics';
import { normalizeDigits } from '@/lib/utils/format';

/** Long enough to span a lunch break and a login round trip; short enough that
 *  a price context does not outlive the day it was true for. */
export const MEMORY_TTL_SECONDS = 6 * 60 * 60;

export interface ConversationMemory {
  /** Catalog category name — «میلگرد». */
  category?: string;
  /** Sub-category display name — «آجدار». */
  sub?: string;
  /** Exact catalog size string — «۱۴». */
  size?: string;
  factory?: string;
  /** Full product name, once one specific SKU has been pinned down. */
  product?: string;
  /** Tonnage the visitor has stated, in tons. */
  tonnage?: number;
  /** Delivery city, matched against the real freight table's city list. */
  city?: string;
  updatedAt: number;
}

const key = (conversationId: string) => `ai-memory:${conversationId}`;

const memory = new Map<string, { value: ConversationMemory; expiresAt: number }>();

function sweep(): void {
  const now = Date.now();
  for (const [k, v] of memory) if (v.expiresAt < now) memory.delete(k);
}

export async function getMemory(conversationId: string | undefined): Promise<ConversationMemory | null> {
  if (!conversationId) return null;
  const hit = memory.get(key(conversationId));
  if (hit && hit.expiresAt > Date.now()) return hit.value;
  return cacheGetJson<ConversationMemory>(key(conversationId)).catch(() => null);
}

/** What a caller may write. `null` clears a field; `undefined` leaves it alone
 *  — the distinction matters, because "this turn said nothing about the city"
 *  and "the visitor withdrew the city" are different events. */
export interface MemoryFacts {
  category?: string | null;
  sub?: string | null;
  size?: string | null;
  factory?: string | null;
  product?: string | null;
  tonnage?: number | null;
  city?: string | null;
}

/** Field-by-field rather than a loop over `Object.entries`: the fields have
 *  two different value types, and an index-signature cast to unify them would
 *  trade a compile-time guarantee for three fewer lines. */
function merge(prior: ConversationMemory, facts: MemoryFacts): ConversationMemory {
  const next: ConversationMemory = { ...prior, updatedAt: Date.now() };
  if (facts.category !== undefined) {
    if (facts.category === null) delete next.category;
    else next.category = facts.category;
  }
  if (facts.sub !== undefined) {
    if (facts.sub === null) delete next.sub;
    else next.sub = facts.sub;
  }
  if (facts.size !== undefined) {
    if (facts.size === null) delete next.size;
    else next.size = facts.size;
  }
  if (facts.factory !== undefined) {
    if (facts.factory === null) delete next.factory;
    else next.factory = facts.factory;
  }
  if (facts.product !== undefined) {
    if (facts.product === null) delete next.product;
    else next.product = facts.product;
  }
  if (facts.tonnage !== undefined) {
    if (facts.tonnage === null) delete next.tonnage;
    else next.tonnage = facts.tonnage;
  }
  if (facts.city !== undefined) {
    if (facts.city === null) delete next.city;
    else next.city = facts.city;
  }
  return next;
}

/**
 * Merge new facts in.
 *
 * MERGE, not replace: a turn that establishes a size must not erase the city
 * three turns ago — that is precisely the "don't make me repeat myself"
 * failure this exists to fix.
 *
 * Every call rewrites the entry even when nothing changed, which is deliberate
 * rather than lazy: the write also refreshes the TTL, so an actively-running
 * conversation keeps its memory alive instead of expiring mid-negotiation on
 * a clock that started at the first turn.
 */
export async function rememberFacts(
  conversationId: string | undefined,
  facts: MemoryFacts,
): Promise<ConversationMemory | null> {
  if (!conversationId) return null;
  const prior = (await getMemory(conversationId)) ?? { updatedAt: 0 };
  const next = merge(prior, facts);
  sweep();
  memory.set(key(conversationId), { value: next, expiresAt: Date.now() + MEMORY_TTL_SECONDS * 1000 });
  await cacheSetJson(key(conversationId), next, MEMORY_TTL_SECONDS).catch(() => {
    /* the in-process copy still serves this instance */
  });
  return next;
}

/* ------------------------------------------------------------------ city -- */

/**
 * The delivery city, read from the visitor's own words.
 *
 * Deterministic and closed-vocabulary on purpose: it matches ONLY against
 * `CITIES`, the same list the freight table is keyed by. A model-extracted
 * city would eventually produce «کرج نو» or a district name, and the very next
 * thing that happens to a city here is that it becomes a road distance and
 * then a Toman freight figure on a card. A city we cannot price is worse than
 * no city, so anything outside the list is simply not a match.
 *
 * Scans NEWEST FIRST: a visitor who says «تهران» and later corrects to
 * «اصفهان» means the second one, and a first-match-wins scan would pin the
 * mistake for the rest of the conversation.
 */
export function detectCity(
  messages: ReadonlyArray<{ role: string; content: string }>,
  cities: ReadonlyArray<{ name: string }> = CITIES,
): string | undefined {
  for (let i = messages.length - 1; i >= 0; i--) {
    const m = messages[i]!;
    if (m.role !== 'user') continue;
    const text = normalizeDigits(m.content);
    // Longest name first so «بندرعباس» is never shadowed by a shorter member.
    const hit = [...cities]
      .sort((a, b) => b.name.length - a.name.length)
      .find((c) => text.includes(c.name));
    if (hit) return hit.name;
  }
  return undefined;
}

/** «۲۰ تن» → 20. Same shape the client's own bulk detection uses, kept here so
 *  the server does not depend on the client having run it. */
export function detectTonnage(
  messages: ReadonlyArray<{ role: string; content: string }>,
): number | undefined {
  for (let i = messages.length - 1; i >= 0; i--) {
    const m = messages[i]!;
    if (m.role !== 'user') continue;
    const match = normalizeDigits(m.content).match(/(\d{1,5}(?:\.\d+)?)\s*تن/);
    if (!match) continue;
    const tons = Number(match[1]);
    if (Number.isFinite(tons) && tons > 0 && tons <= 100_000) return tons;
  }
  return undefined;
}

/* ---------------------------------------------------------------- prompt -- */

/**
 * The memory as one short system line.
 *
 * Written as a STANDING INSTRUCTION, not as a note: «مشخص شده … دوباره نپرس».
 * Stating the facts alone was not enough in practice — the model would read
 * «شهر تحویل: مشهد» and still open its next turn with «شهر تحویل را بگو». The
 * line has to say what to DO with them.
 *
 * Contains no prices and no identity, so it can never license a numeric claim
 * (it is never added to the grounding ledger) and never leaks a customer
 * detail into a prompt cache.
 */
export function memoryFact(mem: ConversationMemory | null): string | null {
  if (!mem) return null;
  const parts: string[] = [];
  if (mem.product) parts.push(`محصول: ${mem.product}`);
  else {
    if (mem.category) parts.push(`دستهٔ محصول: ${mem.category}`);
    if (mem.sub) parts.push(`نوع: ${mem.sub}`);
  }
  if (mem.size) parts.push(`سایز: ${mem.size}`);
  if (mem.factory) parts.push(`کارخانه: ${mem.factory}`);
  if (mem.tonnage) parts.push(`مقدار: ${mem.tonnage} تن`);
  if (mem.city) parts.push(`شهر تحویل: ${mem.city}`);
  if (parts.length === 0) return null;
  return (
    `در همین گفتگو این‌ها قبلاً مشخص شده‌اند: ${parts.join('، ')}. ` +
    'هیچ‌کدام از این‌ها را دوباره از کاربر نپرس؛ همین‌ها را در صدا زدن ابزارها به کار ببر. ' +
    'فقط اگر خودِ کاربر مقدار تازه‌ای گفت، همان تازه را جایگزین کن.'
  );
}
