import { chromium } from '@playwright/test';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const msgs=[];
page.on('console', m => { if(m.type()==='error'||m.type()==='warning') msgs.push(`[${m.type()}] ${m.text().slice(0,300)}`); });
page.on('pageerror', e => msgs.push(`[pageerror] ${e.message.slice(0,300)}`));
await page.goto('http://localhost:3000/', { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
console.log(msgs.length? msgs.join('\n\n') : 'NO console errors/warnings');
await browser.close();
